/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software.
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 *
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor:
 * Prof. Dr. Igor A. Lourenço da Silva)
 *
 * Copyright (C) 2015 Gabriel Ed. da Silva
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
 * http://www.gnu.org/licenses/.
 */
package com.lrsb.model;

import static com.lrsb.model.StringTreatment.*;

/**
 * Classe responsável por armazenar um segmento da representação linear.
 *
 * @author gabriel
 */
public class Segment {

    private Integer microUnitId;
    private String linearRepresentation;
    private Integer pause;
    private Integer start;
    private Integer end;
    private Integer durationM;
    private Integer fixCountS;
    private Integer fixDurationS;
    private Double meanDurationS;
    private Integer fixCountT;
    private Integer fixDurationT;
    private Double meanDurationT;
    private Integer fixCountST;
    private Integer fixDurationST;
    private Double meanDurationST;
    private Integer fixCountSPause;
    private Integer fixDurationSPause;
    private Double meanDurationSPause;
    private Integer fixCountTPause;
    private Integer fixDurationTPause;
    private Double meanDurationTPause;
    private Integer fixCountSTPause;
    private Integer fixDurationSTPause;
    private Double meanDurationSTPause;
    private Integer visits;
    private Integer visitsPause;
    private String saccade;
    private String sacaddeAngle;
    private Double saccadeSum;
    private Double saccadeMean;
    private String saccadePause;
    private String saccadeAnglePause;
    private Double saccadeSumPause;
    private Double saccadeMeanPause;
    private Integer ins;
    private Integer del;

    /**
     * Método get do campo saccadeAnglePause.
     * @return Retorna o valor do campo saccadeAnglePause.
     */
    public String getSaccadeAnglePause() {
        return saccadeAnglePause;
    }

    /**
     * Método set do campo saccadeAnglePause.
     * @param saccadeAnglePause Novo valor para o campo saccadeAnglePause.
     */
    public void setSaccadeAnglePause(String saccadeAnglePause) {
        this.saccadeAnglePause = saccadeAnglePause;
    }

    /**
     * Método get do campo microUnitId.
     * @return Retorna o valor do campo microUnitId.
     */
    public Integer getMicroUnitId() {
        return microUnitId;
    }

    /**
     * Método set do campo microUnitId.
     * @param microUnitId Novo valor para o campo microUnitId.
     */
    public void setMicroUnitId(Integer microUnitId) {
        this.microUnitId = microUnitId;
    }

    /**
     * Método get do campo linearRepresentation.
     * @return Retorna o valor do campo linearRepresentation.
     */
    public String getLinearRepresentation() {
        return linearRepresentation;
    }

    /**
     * Método set do campo linearRepresentation.
     * @param linearRepresentation Novo valor para o campo linearRepresentation.
     */
    public void setLinearRepresentation(String linearRepresentation) {
        this.linearRepresentation = linearRepresentation;
    }

    /**
     * Método get do campo pause.
     * @return Retorna o valor do campo pause.
     */
    public Integer getPause() {
        return pause;
    }

    /**
     * Método set do campo pause.
     * @param pause Novo valor para o campo pause.
     */
    public void setPause(Integer pause) {
        this.pause = pause;
    }

    /**
     * Método get do campo start.
     * @return Retorna o valor do campo start.
     */
    public Integer getStart() {
        return start;
    }

    /**
     * Método set do campo start.
     * @param start Novo valor para o campo start.
     */
    public void setStart(Integer start) {
        this.start = start;
    }

    /**
     * Método get do campo end.
     * @return Retorna o valor do campo end.
     */
    public Integer getEnd() {
        return end;
    }

    /**
     * Método set do campo end.
     * @param end Novo valor para o campo end.
     */
    public void setEnd(Integer end) {
        this.end = end;
    }

    /**
     * Método get do campo durationM.
     * @return Retorna o valor do campo durationM.
     */
    public Integer getDurationM() {
        return durationM;
    }

    /**
     * Método set do campo durationM.
     * @param durationM Novo valor para o campo durationM.
     */
    public void setDurationM(Integer durationM) {
        this.durationM = durationM;
    }

    /**
     * Método get do campo fixCountS.
     * @return Retorna o valor do campo fixCountS.
     */
    public Integer getFixCountS() {
        return fixCountS;
    }

    /**
     * Método set do campo fixCountS.
     * @param fixCountS Novo valor para o campo fixCountS.
     */
    public void setFixCountS(Integer fixCountS) {
        this.fixCountS = fixCountS;
    }

    /**
     * Método get do campo fixDurationS.
     * @return Retorna o valor do campo fixDurationS.
     */
    public Integer getFixDurationS() {
        return fixDurationS;
    }

    /**
     * Método set do campo fixDurationS.
     * @param fixDurationS Novo valor para o campo fixDurationS.
     */
    public void setFixDurationS(Integer fixDurationS) {
        this.fixDurationS = fixDurationS;
    }

    /**
     * Método get do campo fixCountT.
     * @return Retorna o valor do campo fixCountT.
     */
    public Integer getFixCountT() {
        return fixCountT;
    }

    /**
     * Método set do campo fixCountT.
     * @param fixCountT Novo valor para o campo fixCountT.
     */
    public void setFixCountT(Integer fixCountT) {
        this.fixCountT = fixCountT;
    }

    /**
     * Método get do campo fixDurationT.
     * @return Retorna o valor do campo fixDurationT.
     */
    public Integer getFixDurationT() {
        return fixDurationT;
    }

    /**
     * Método set do campo fixDurationT.
     * @param fixDurationT Novo valor para o campo fixDurationT.
     */
    public void setFixDurationT(Integer fixDurationT) {
        this.fixDurationT = fixDurationT;
    }

    /**
     * Método get do campo meanDurationT.
     * @return Retorna o valor do campo meanDurationT.
     */
    public Double getMeanDurationT() {
        return meanDurationT;
    }

    /**
     * Método set do campo meanDurationT.
     * @param meanDurationT Novo valor para o campo meanDurationT.
     */
    public void setMeanDurationT(Double meanDurationT) {
        this.meanDurationT = meanDurationT;
    }

    /**
     * Método get do campo fixCountST.
     * @return Retorna o valor do campo fixCountST.
     */
    public Integer getFixCountST() {
        return fixCountST;
    }

    /**
     * Método set do campo fixCountST.
     * @param fixCountST Novo valor para o campo fixCountST.
     */
    public void setFixCountST(Integer fixCountST) {
        this.fixCountST = fixCountST;
    }

    /**
     * Método get do campo fixDurationST.
     * @return tRetorna o valor do campo fixDurationST.
     */
    public Integer getFixDurationST() {
        return fixDurationST;
    }

    /**
     * Método set do campo fixDurationST.
     * @param fixDurationST Novo valor para o campo fixDurationST.
     */
    public void setFixDurationST(Integer fixDurationST) {
        this.fixDurationST = fixDurationST;
    }

    /**
     * Método get do campo fixCountSPause.
     * @return Retorna o valor do campo fixCountSPause.
     */
    public Integer getFixCountSPause() {
        return fixCountSPause;
    }

    /**
     * Método set do campo fixCountSPause.
     * @param fixCountSPause Novo valor para o campo fixCountSPause.
     */
    public void setFixCountSPause(Integer fixCountSPause) {
        this.fixCountSPause = fixCountSPause;
    }

    /**
     * Método get do campo fixDurationSPause.
     * @return Retorna o valor do campo fixDurationSPause.
     */
    public Integer getFixDurationSPause() {
        return fixDurationSPause;
    }

    /**
     * Método set do campo fixDurationSPause.
     * @param fixDurationSPause Novo valor para o campo fixDurationSPause.
     */
    public void setFixDurationSPause(Integer fixDurationSPause) {
        this.fixDurationSPause = fixDurationSPause;
    }

    /**
     * Método get do campo meanDurationSPause.
     * @return Retorna o valor do campo meanDurationSPause.
     */
    public Double getMeanDurationSPause() {
        return meanDurationSPause;
    }

    /**
     * Método set do campo meanDurationSPause.
     * @param meanDurationSPause Novo valor para o campo meanDurationSPause.
     */
    public void setMeanDurationSPause(Double meanDurationSPause) {
        this.meanDurationSPause = meanDurationSPause;
    }

    /**
     * Método get do campo fixCountTPause.
     * @return Retorna o valor do campo fixCountTPause.
     */
    public Integer getFixCountTPause() {
        return fixCountTPause;
    }

    /**
     * Método set do campo fixCountTPause.
     * @param fixCountTPause Novo valor para o campo fixCountTPause.
     */
    public void setFixCountTPause(Integer fixCountTPause) {
        this.fixCountTPause = fixCountTPause;
    }

    /**
     * Método get do campo fixDurationTPause.
     * @return Retorna o valor do campo fixDurationTPause.
     */
    public Integer getFixDurationTPause() {
        return fixDurationTPause;
    }

    /**
     * Método set do campo fixDurationTPause.
     * @param fixDurationTPause Novo valor para o campo fixDurationTPause.
     */
    public void setFixDurationTPause(Integer fixDurationTPause) {
        this.fixDurationTPause = fixDurationTPause;
    }

    /**
     * Método get do campo meanDurationTPause.
     * @return Retorna o valor do campo meanDurationTPause.
     */
    public Double getMeanDurationTPause() {
        return meanDurationTPause;
    }

    /**
     * Método set do campo meanDurationTPause.
     * @param meanDurationTPause Novo valor para o campo meanDurationTPause.
     */
    public void setMeanDurationTPause(Double meanDurationTPause) {
        this.meanDurationTPause = meanDurationTPause;
    }

    /**
     * Método get do campo fixCountSTPause.
     * @return Retorna o valor do campo fixCountSTPause.
     */
    public Integer getFixCountSTPause() {
        return fixCountSTPause;
    }

    /**
     * Método set do campo fixCountSTPause.
     * @param fixCountSTPause Novo valor para o campo fixCountSTPause.
     */
    public void setFixCountSTPause(Integer fixCountSTPause) {
        this.fixCountSTPause = fixCountSTPause;
    }

    /**
     * Método get do campo fixDurationSTPause.
     * @return Retorna o valor do campo fixDurationSTPause.
     */
    public Integer getFixDurationSTPause() {
        return fixDurationSTPause;
    }

    /**
     * Método set do campo fixDurationSTPause.
     * @param fixDurationSTPause Novo valor para o campo fixDurationSTPause.
     */
    public void setFixDurationSTPause(Integer fixDurationSTPause) {
        this.fixDurationSTPause = fixDurationSTPause;
    }

    /**
     * Método get do campo meanDurationSTPause.
     * @return Retorna o valor do campo meanDurationSTPause.
     */
    public Double getMeanDurationSTPause() {
        return meanDurationSTPause;
    }

    /**
     * Método set do campo meanDurationSTPause.
     * @param meanDurationSTPause Novo valor para o campo meanDurationSTPause.
     */
    public void setMeanDurationSTPause(Double meanDurationSTPause) {
        this.meanDurationSTPause = meanDurationSTPause;
    }

    /**
     * Método get do campo visits.
     * @return Retorna o valor do campo visits.
     */
    public Integer getVisits() {
        return visits;
    }

    /**
     * Método set do campo visits.
     * @param visits Novo valor para o campo visits.
     */
    public void setVisits(Integer visits) {
        this.visits = visits;
    }

    /**
     * Método get do campo visitsPause.
     * @return Retorna o valor do campo visitsPause.
     */
    public Integer getVisitsPause() {
        return visitsPause;
    }

    /**
     * Método set do campo visitsPause.
     * @param visitsPause Novo valor para o campo visitsPause.
     */
    public void setVisitsPause(Integer visitsPause) {
        this.visitsPause = visitsPause;
    }

    /**
     * Método get do campo saccade.
     * @return Retorna o valor do campo saccade.
     */
    public String getSaccade() {
        return saccade;
    }

    /**
     * Método set do campo saccade.
     * @param saccade Novo valor para o campo saccade.
     */
    public void setSaccade(String saccade) {
        this.saccade = saccade;
    }

    /**
     * Método get do campo sacaddeAngle.
     * @return Retorna o valor do campo sacaddeAngle.
     */
    public String getSacaddeAngle() {
        return sacaddeAngle;
    }

    /**
     * Método set do campo sacaddeAngle.
     * @param sacaddeAngle Novo valor para o campo sacaddeAngle.
     */
    public void setSacaddeAngle(String sacaddeAngle) {
        this.sacaddeAngle = sacaddeAngle;
    }

    /**
     * Método get do campo saccadeSum.
     * @return Retorna o valor do campo saccadeSum.
     */
    public Double getSaccadeSum() {
        return saccadeSum;
    }

    /**
     * Método set do campo saccadeSum.
     * @param saccadeSum Novo valor para o campo saccadeSum.
     */
    public void setSaccadeSum(Double saccadeSum) {
        this.saccadeSum = saccadeSum;
    }

    /**
     * Método get do campo saccadeMean.
     * @return Retorna o valor do campo saccadeMean.
     */
    public Double getSaccadeMean() {
        return saccadeMean;
    }

    /**
     * Método set do campo saccadeMean.
     * @param saccadeMean Novo valor para o campo saccadeMean.
     */
    public void setSaccadeMean(Double saccadeMean) {
        this.saccadeMean = saccadeMean;
    }

    /**
     * Método get do campo saccadePause.
     * @return Retorna o valor do campo saccadePause.
     */
    public String getSaccadePause() {
        return saccadePause;
    }

    /**
     * Método set do campo saccadePause.
     * @param saccadePause Novo valor para o campo saccadePause.
     */
    public void setSaccadePause(String saccadePause) {
        this.saccadePause = saccadePause;
    }

    /**
     * Método get do campo saccadeSumPause.
     * @return Retorna o valor do campo saccadeSumPause.
     */
    public Double getSaccadeSumPause() {
        return saccadeSumPause;
    }

    /**
     * Método set do campo saccadeSumPause.
     * @param saccadeSumPause Novo valor para o campo saccadeSumPause.
     */
    public void setSaccadeSumPause(Double saccadeSumPause) {
        this.saccadeSumPause = saccadeSumPause;
    }

    /**
     * Método get do campo saccadeMeanPause.
     * @return Retorna o valor do campo saccadeMeanPause.
     */
    public Double getSaccadeMeanPause() {
        return saccadeMeanPause;
    }

    /**
     * Método set do campo saccadeMeanPause.
     * @param saccadeMeanPause Novo valor para o campo saccadeMeanPause.
     */
    public void setSaccadeMeanPause(Double saccadeMeanPause) {
        this.saccadeMeanPause = saccadeMeanPause;
    }

    /**
     * Método get do campo ins.
     * @return Retorna o valor do campo ins.
     */
    public Integer getIns() {
        return ins;
    }

    /**
     * Método set do campo ins.
     * @param ins Novo valor para o campo ins.
     */
    public void setIns(Integer ins) {
        this.ins = ins;
    }

    /**
     * Método get do campo del.
     * @return Retorna o valor do campo del.
     */
    public Integer getDel() {
        return del;
    }

    /**
     * Método set do campo del.
     * @param del Novo valor para o campo del.
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * Método get do campo meanDurationS.
     * @return Retorna o valor do campo meanDurationS.
     */
    public Double getMeanDurationS() {
        return meanDurationS;
    }

    /**
     * Método set do campo meanDurationS.
     * @param meanDurationS Novo valor para o campo meanDurationS.
     */
    public void setMeanDurationS(Double meanDurationS) {
        this.meanDurationS = meanDurationS;
    }

    /**
     * Método get do campo meanDurationST.
     * @return Retorna o valor do campo meanDurationST.
     */
    public Double getMeanDurationST() {
        return meanDurationST;
    }

    /**
     * Método set do campo meanDurationST.
     * @param meanDurationST Novo valor para o campo meanDurationST.
     */
    public void setMeanDurationST(Double meanDurationST) {
        this.meanDurationST = meanDurationST;
    }

    /**
     * Prepara as informações do segmento para o formato de linha do arquivo CSV.
     * @return Segmento formatado como linha do arquivo CSV.
     */
    public String segmentToCSV() {
        return microUnitId + "," + "\"" + replaceSpaces(linearRepresentation) + "\"" + "," + pause + "," + start + "," + end
                + "," + durationM + "," + fixCountS + "," + fixDurationS
                + "," + format2f(meanDurationS) + "," + fixCountT + "," + fixDurationT + "," + format2f(meanDurationT)
                + "," + fixCountST + "," + fixDurationST + "," + format2f(meanDurationST) + "," + fixCountSPause
                + "," + fixDurationSPause + "," + format2f(meanDurationSPause) + "," + fixCountTPause
                + "," + fixDurationTPause + "," + format2f(meanDurationTPause) + "," + fixCountSTPause
                + "," + fixDurationSTPause + "," + format2f(meanDurationSTPause) + "," + visits + "," + visitsPause
                + "," + saccade + "," + sacaddeAngle + "," + format2f(saccadeSum) + "," + format2f(saccadeMean)
                + "," + saccadePause + "," + saccadeAnglePause + "," + format2f(saccadeSumPause)
                + "," + format2f(saccadeMeanPause) + "," + ins + "," + del + "\n";
    }
}
