/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software.
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 *
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor:
 * Prof. Dr. Igor A. Lourenço da Silva)
 *
 * Copyright (C) 2015 Gabriel Ed. da Silva
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
 * http://www.gnu.org/licenses/.
 */
package com.lrsb.xmlElements;

/**
 * Classe responsável por armazenar as fixações.
 *
 * @author gabriel
 */
public class Fix implements XmlEvent {

    /**
     * Tempo da fixação
     */
    protected Integer time;

    /**
     * Tempo total da fixação
     */
    protected Integer tt;

    /**
     * Janela da Fixação
     */
    protected Integer win;

    /**
     * Cursor
     */
    protected Integer cursor;

    /**
     * Construtor vazio
     */
    public Fix() {
    }

    /**
     * Construtor da classe fix.
     *
     * @param time - Tempo
     * @param tt - Tempo Total
     * @param win - Janela
     * @param cursor - Cursor
     */
    public Fix(Integer time, Integer tt, Integer win, Integer cursor) {
        this.time = time;
        this.tt = tt;
        this.win = win;
        this.cursor = cursor;
    }

    /**
     * Método get da variável time
     *
     * @return the time
     */
    @Override
    public Integer getTime() {
        return time;
    }

    /**
     * Método set da variável time
     *
     * @param time the time to set
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * Método get da variável tt
     *
     * @return the tt
     */
    public Integer getTt() {
        return tt;
    }

    /**
     * Método set da variável tt
     *
     * @param tt the tt to set
     */
    public void setTt(Integer tt) {
        this.tt = tt;
    }

    /**
     * Método get da variável Win
     *
     * @return the win
     */
    public Integer getWin() {
        return win;
    }

    /**
     * Método set da variável Win
     *
     * @param win the win to set
     */
    public void setWin(Integer win) {
        this.win = win;
    }

    /**
     * Método get da variável cursor
     *
     * @return the cursor
     */
    public Integer getCursor() {
        return cursor;
    }

    /**
     * Método get da variável cursor
     *
     * @param cursor the cursor to set
     */
    public void setCursor(Integer cursor) {
        this.cursor = cursor;
    }
}
