/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software.
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 *
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor:
 * Prof. Dr. Igor A. Lourenço da Silva)
 *
 * Copyright (C) 2015 Gabriel Ed. da Silva
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
 * http://www.gnu.org/licenses/.
 */
package com.lrsb.xmlElements;

/**
 * Classe responsável por armazenar as ações de tecla do documento processado.
 * @author gabriel
 */
public class Key extends Action {

    /**
     * Tipo de ação de tecla.
     */
    private String type;

    /**
     * Largura.
     */
    private Integer width;

    /**
     * Altura.
     */
    private Integer height;

    /**
     * Construtor da clase Key. Herda da classe Action.
     *
     * @param time Tempo que ocorreu a ação de tecla.
     * @param cursor Cursor.
     * @param value Valor da tecla acionada.
     * @param action Tipo de ação (Mouse ou Key).
     * @param type Tipo de ação realizada (Insert ou Delete).
     * @param width Largura.
     * @param height Altura.
     */
    public Key(Integer time, Integer cursor, String value, String action, String type, Integer width, Integer height) {
        super(time, cursor, value, action);
        this.type = type;
        this.width = width;
        this.height = height;
    }

    /**
     * Método get da variável Type.
     *
     * @return Retorna o valor do campo type.
     */
    public String getType() {
        return type;
    }

    /**
     * Método set da variável type.
     *
     * @param type Novo valor do campo type.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Método get da variável width.
     *
     * @return Retorna o valor do campo width.
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * Método set da variável width.
     *
     * @param width Novo valor do campo width.
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * Método get da variável height.
     *
     * @return Retorna o valor do campo height.
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * Método set da variável height.
     *
     * @param height Novo valor do campo height.
     */
    public void setHeight(Integer height) {
        this.height = height;
    }
}
