/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software. 
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 * 
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor: 
 * Prof. Dr. Igor A. Lourenço da Silva)
 * 
 * Copyright (C) 2015 Gabriel Ed. da Silva
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General 
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
* http://www.gnu.org/licenses/.
 */

package com.lrsb.xmlElements;

/**
 *
 * @author gabriel
 */
public class TextFix extends Fix {

    private Integer block;
    private String text;
    private Integer x;
    private Integer y;
    private Integer dur;

    /**
     * Construtor Vazio
     */
    public TextFix() {
    }

    /**
     * Construtor da classe TextFix.
     * @param time
     * @param tt
     * @param win
     * @param cursor
     * @param block
     * @param text
     * @param x
     * @param y
     * @param dur
     */
    public TextFix(Integer time, Integer tt, Integer win, Integer cursor, Integer block, String text, Integer x, Integer y, Integer dur) {
        super(time, tt, win,cursor);
        this.cursor = cursor;
        this.block = block;
        this.text = text;
        this.x = x;
        this.y = y;
        this.dur = dur;
    }

    /**
     * Método get da variável block
     * @return the block
     */
    public Integer getBlock() {
        return block;
    }

    /**
     * Método set da variável block
     * @param block the block to set
     */
    public void setBlock(Integer block) {
        this.block = block;
    }

    /**
     * Método get da variável text
     * @return the text
     */
    public String getText() {
        return text;
    }

    /**
     * Método set da variável text
     * @param text the text to set
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Método get da variável x
     * @return the x
     */
    public Integer getX() {
        return x;
    }

    /**
     * Método set da variável x
     * @param x the x to set
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * Método get da variável y
     * @return the y
     */
    public Integer getY() {
        return y;
    }

    /**
     * Método set da variável y
     * @param y the y to set
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * Método get da variável dur
     * @return the dur
     */
    public Integer getDur() {
        return dur;
    }

    /**
     * Método set da variável dur
     * @param dur the dur to set
     */
    public void setDur(Integer dur) {
        this.dur = dur;
    }

}
