/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software.
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 *
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor:
 * Prof. Dr. Igor A. Lourenço da Silva)
 *
 * Copyright (C) 2015 Gabriel Ed. da Silva
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
 * http://www.gnu.org/licenses/.
 */
package com.lrsb.xmlElements;

import java.util.ArrayList;

/**
 * Classe responsável por armazenar as informaçõe do documento XML processado.
 * @author gabriel
 */
public class XmlDocument {
    /**
     * Assunto do documento processado.
     */
    private String subject;
    
    /**
     * Tarefa realizada no documento processado. As tarefas podem ser de 
     * pós-edição (post-editing) ou tradução (translation).
     */
    private String task;
    
    /**
     * Documento fonte.
     */
    
    private String sourceText;
    
    /**
     * Idioma do documento fonte.
     */
    private String sourceLanguage;
    
    /**
     * Idioma do documento alvo.
     */
    private String targetLanguage;
    
    /**
     * Tempo decorrido ao término da tarefa.
     */
    private Integer stopTime;
    
    /**
     * Lista com as fixações do documento processado.
     */
    
    private ArrayList<Fix> fixationList = new ArrayList<>();
    
    /**
     * Lista com as ações do documento processado.
     */
    private ArrayList<Action> actionList = new ArrayList<>();

    /**
     * Método get da variável subject.
     *
     * @return Retorna o valor do campo subject.
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Método set da variável subject.
     *
     * @param subject Novo valor para o campo subject.
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * Método get da variável task.
     *
     * @return Retorna o valor do campo task.
     */
    public String getTask() {
        return task;
    }

    /**
     * Método set da variável task.
     *
     * @param task Novo valor para o campo task.
     */
    public void setTask(String task) {
        this.task = task;
    }

    /**
     * Método get da variável sourceText.
     *
     * @return Retorna o valor do campo sourceText.
     */
    public String getSourceText() {
        return sourceText;
    }

    /**
     * Método set da variável sourceText.
     *
     * @param sourceText Novo valor para o campo sourceText.
     */
    public void setSourceText(String sourceText) {
        this.sourceText = sourceText;
    }

    /**
     * Método get da variável STlanguage.
     *
     * @return Retorna o valor do campo sourceLanguage.
     */
    public String getSourceLanguage() {
        return sourceLanguage;
    }

    /**
     * Método set da variável STlanguage.
     *
     * @param sourceLanguage Novo valor para o campo sourceLanguage.
     */
    public void setSourceLanguage(String sourceLanguage) {
        this.sourceLanguage = sourceLanguage;
    }

    /**
     * Método get da variável TTlanguage.
     *
     * @return Retorna o valor do campo targetLanguage.
     */
    public String getTargetLanguage() {
        return targetLanguage;
    }

    /**
     * Método set da variável TTlanguage.
     *
     * @param targetLanguage Novo valor para o campo targetLanguage.
     */
    public void setTargetLanguage(String targetLanguage) {
        this.targetLanguage = targetLanguage;
    }

    /**
     * Método get da variável stopTime.
     *
     * @return Retorna o valor do campo stopTime.
     */
    public Integer getStopTime() {
        return stopTime;
    }

    /**
     * Método set da variável stopTime.
     *
     * @param stopTime Novo valor para o campo stopTime.
     */
    public void setStopTime(Integer stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * Método get da lista fixationList.
     *
     * @return Retorna um array com objetos Fix.
     */
    public ArrayList<Fix> getFixationList() {
        return fixationList;
    }

    /**
     * Método set da lista fixationList.
     *
     * @param fixationList Novo array com objetiso do tipo Fix para o campo fixationList.
     */
    private void setFixationList(ArrayList<Fix> fixationList) {
        this.fixationList = fixationList;
    }

    /**
     * Método get da lista actionList.
     *
     * @return Retorna um array com objetos Action.
     */
    public ArrayList<Action> getActionList() {
        return actionList;
    }

    /**
     * Método set da variável actionList.
     *
     * @param actionList Novo array com objetiso do tipo Action para o campo 
     * actionList.
     */
    private void setActionList(ArrayList<Action> actionList) {
        this.actionList = actionList;
    }
}
