/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software. 
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 * 
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor: 
 * Prof. Dr. Igor A. Lourenço da Silva)
 * 
 * Copyright (C) 2015 Gabriel Ed. da Silva
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General 
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
* http://www.gnu.org/licenses/.
 */

package com.lrsb.view;

import com.lrsb.config.Config;
import com.lrsb.model.Document;
import com.lrsb.model.Processor;
import com.lrsb.spreadsheet.SaveToCSV;
import com.lrsb.xmlElements.XmlDocument;
import com.lrsb.xmlElements.XmlReader;
import java.io.File;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.control.ToggleButton;
import javafx.stage.DirectoryChooser;
import javafx.stage.Stage;

/**
 *
 * @author gabriel
 */
public class MainScreenController implements Initializable {

    @FXML
    private TextField resourcePathTF;
    @FXML
    private TextField targetPathTF;

    @FXML
    private TextField pauseBegin;

    @FXML
    private TextField pauseEnd;
    
    @FXML
    private ToggleButton fullDirectory;
    
    @FXML
    private Button start;
    
    @FXML
    private Button reset;

    @FXML
    private void resourcePathSearch(ActionEvent event) {
        DirectoryChooser dc = new DirectoryChooser();
        dc.setTitle("Resource Directory");
        File file = dc.showDialog(new Stage());
        resourcePathTF.setText(file.toString());
    }

    @FXML
    private void targetPathSearch(ActionEvent event) {
        DirectoryChooser dc = new DirectoryChooser();
        dc.setTitle("Target Directory");
        File file = dc.showDialog(new Stage());
        targetPathTF.setText(file.toString());
    }
    
    @FXML
    public void setValues(){
        Config cfg = Config.getInstance();
        this.fullDirectory.setSelected(cfg.isFullDirectory());
        this.pauseBegin.setText(cfg.getDefaultPauseBegin());
        this.pauseEnd.setText(cfg.getDefaultPauseEnd());
        this.targetPathTF.setText(cfg.defaultPath);
        this.resourcePathTF.setText("");
    }
    
    @FXML
    public void startProcess(){
        try {
            Processor.process(resourcePathTF.getText(),targetPathTF.getText(),pauseBegin.getText(),
                    pauseEnd.getText(),fullDirectory.isSelected());
        } catch (Exception ex) {
            Logger.getLogger(MainScreenController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @FXML
    public void reset(ActionEvent event){
        setValues();
    }
    
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        setValues();
    }

}
