/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software. 
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 * 
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor: 
 * Prof. Dr. Igor A. Lourenço da Silva)
 * 
 * Copyright (C) 2015 Gabriel Ed. da Silva
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General 
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
* http://www.gnu.org/licenses/.
 */

package com.lrsb.view;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.MenuItem;

/**
 *
 * @author gabriel
 */
public class MenuBarController implements Initializable {

    @FXML
    private MenuItem preferences;
    
    @FXML
    private MenuItem tutorial;
    
    @FXML
    private MenuItem about;
    
    @FXML
    private MenuItem quit;

    @FXML
    private void openMenu(){
        Stages.getInstance().showMenu();
    }
    
    @FXML
    private void quit(){
        System.exit(0);
    }
    
    @FXML
    private void openTutorial(){
        Stages.getInstance().showTutorialStage();
    }
    
    @FXML
    private void openAbout(){
        try {
            java.awt.Desktop.getDesktop().browse(new URI("http://www.gabrieleduardo.me/LRSB"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(MenuBarController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    
    @Override
    public void initialize(URL url, ResourceBundle rb) {
    }

}
