/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software. 
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 * 
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor: 
 * Prof. Dr. Igor A. Lourenço da Silva)
 * 
 * Copyright (C) 2015 Gabriel Ed. da Silva
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General 
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
* http://www.gnu.org/licenses/.
 */

package com.lrsb.view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.MenuBar;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;

/**
 * Classe responsável por armazenar os stages.
 * @author gabriel
 */
public class Stages {

    private final String tutorial = "http://www.gabrieleduardo.me/LRSB/";
    
    private final Stage stage;
    private final Stage browserStage;
    private Scene mainScene;
    private Scene menuScene;
    private Scene tutorialScene;
    private BorderPane primaryScreen;
    private BorderPane primaryScreen2;
    private MenuBar menuBar;
    private MenuBar menuBar2;
    private AnchorPane mainScreen;
    private AnchorPane menuScreen;

    private Stages() {
        this.stage = new Stage();
        this.browserStage = new Stage();
        initAll();
    }

    private void initAll() {
        try {
            // Inicia as telas
            this.stage.setResizable(false);
            this.stage.setTitle("Linear Representation Spreadsheet Builder");
            FXMLLoader loader = new FXMLLoader(Main.class.getResource("PrimaryScreen.fxml"));
            primaryScreen = (BorderPane) loader.load();
            loader = new FXMLLoader(Main.class.getResource("PrimaryScreen.fxml"));
            primaryScreen2 = (BorderPane) loader.load();

            // Inicia a barra de menu
            loader = new FXMLLoader(Main.class.getResource("MenuBar.fxml"));
            menuBar = (MenuBar) loader.load();
            loader = new FXMLLoader(Main.class.getResource("MenuBar.fxml"));
            menuBar2 = (MenuBar) loader.load();
            // Inicia a tela principal
            loader = new FXMLLoader(Main.class.getResource("MainScreen.fxml"));
            mainScreen = (AnchorPane) loader.load();
            // Inicia a tela de menu
            loader = new FXMLLoader(Main.class.getResource("MenuScreen.fxml"));
            menuScreen = (AnchorPane) loader.load();

            // Configura a tela principal
            primaryScreen.setTop(menuBar);
            primaryScreen.setCenter(mainScreen);
            mainScene = new Scene(primaryScreen);
            mainScene.setRoot(primaryScreen);
            // Configura a tela de menu
            primaryScreen2.setTop(menuBar2);
            primaryScreen2.setCenter(menuScreen);
            menuScene = new Scene(primaryScreen2);
            menuScene.setRoot(primaryScreen2);

            // Inicia o Browser
            
            WebView browser = new WebView();
            WebEngine webEngine = browser.getEngine();
            webEngine.load(tutorial);
            tutorialScene = new Scene(browser);

            showMain();
        } catch (IOException ex) {
            Logger.getLogger(Stages.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void showTutorialStage(){
        browserStage.setScene(tutorialScene);
        this.browserStage.show();
    }

    public void showStage() {
        this.stage.show();
    }

    public void showMain() {
        stage.setScene(mainScene);
    }

    public void showMenu() {
        stage.setScene(menuScene);
    }

    public static Stages getInstance() {
        return Stages2Holder.INSTANCE;
    }

    private static class Stages2Holder {

        private static final Stages INSTANCE = new Stages();
    }
}
