/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software. 
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 * 
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor: 
 * Prof. Dr. Igor A. Lourenço da Silva)
 * 
 * Copyright (C) 2015 Gabriel Ed. da Silva
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General 
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
* http://www.gnu.org/licenses/.
 */

package com.lrsb.spreadsheet;

import com.lrsb.model.ConsolidatedDocument;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * TODO
 * 
 * @author gabriel
 */

/**
 * RF18
 * @author gabriel
 */
public class SaveToCSVConsolidated {
    
    private static String header = "sep=,\n"
            +"Subject,TotalDuration, TotalFixCountS, TotalFixDurS, TotalMeanFixS,"
            +"TotalFixCountT, TotalFixDurT, TotalMeanFixT, TotalFixCountST, TotalFixDurS&T,"
            +"TotalMeanFixST, TotalVisits, TotalIns, TotalDel, TotalSaccade, TotalMeanSaccade," 
            +"TotalSaccadeSize, PtotalFixCountS,PtotalFixDurS, PtotalMeanFixS," 
            +"PtotalFixCountT,PtotalFixDurT, PtotalMeanFixT, PtotalFixCountST,PtotalVisits,"
            +"TotalSaccade, TotalMeanSaccade,TotalSaccadeSize";
    
    public static void save(ConsolidatedDocument doc, String filePath) {
        try {
            FileWriter fw = new FileWriter(filePath);
            fw.append(header);
            fw.append(doc.documentToCSV());
            fw.close();

        } catch (IOException ex) {
            Logger.getLogger(SaveToCSV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
