/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software. 
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 * 
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor: 
 * Prof. Dr. Igor A. Lourenço da Silva)
 * 
 * Copyright (C) 2015 Gabriel Ed. da Silva
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General 
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
* http://www.gnu.org/licenses/.
 */

package com.lrsb.spreadsheet;

import com.lrsb.model.Document;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gabriel
 */
public class SaveToCSV {
    
    /**
     * Cabeçalho do arquivo CSV.
     */

    private static final String header = "sep=,\n"
            + "Subject,Task,ST,STlanguage,TTlanguage,"
            + "MicroUnitId,LinearRep,Pause,Start,End,"
            + "DurationM,FixCountS,FixDurationS,MeanDurationS,FixCountT,"
            + "FixDurationT,MeanDurationT,FixCountST,FixDurationST,MeanDurationST,"
            + "FixCountSPause,FixDurationSPause,MeanDurationSPause,FixCountTPause,"
            + "FixDurationTPause,MeanDurationTPause,FixCountSTPause,FixDurationSTPause,"
            + "MeanDurationSTPause,Visits,VisitsPause,Saccade,SacaddeAngle,SaccadeSum,"
            + "SaccadeMean,SaccadePause,SaccadeAnglePause,SaccadeSumPause,SaccadeMeanPause,"
            + "ins,del\n";

    /**
     * 
     * @param doc
     * @param filePath 
     */
    
    public static void save(Document doc, String filePath) {
        try {
            FileWriter fw = new FileWriter(filePath);
            fw.append(header);
            fw.append(doc.documentToCSV());
            fw.close();

        } catch (IOException ex) {
            Logger.getLogger(SaveToCSV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * 
     * @param docList
     * @param filePath 
     */
    
    public static void saveSinglefile(ArrayList<Document> docList, String filePath) {
        try {
            FileWriter fw = new FileWriter(filePath);
            fw.append(header);
            for(Document doc : docList){
                fw.append(doc.documentToCSV());
            }
            fw.close();

        } catch (IOException ex) {
            Logger.getLogger(SaveToCSV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
