/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software. 
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 * 
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor: 
 * Prof. Dr. Igor A. Lourenço da Silva)
 * 
 * Copyright (C) 2015 Gabriel Ed. da Silva
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General 
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
* http://www.gnu.org/licenses/.
 */

package com.lrsb.xmlElements;

/**
 *
 * @author gabriel
 */
public class Key extends Action {
    
    /**
     * Tipo de ação de tecla
     */
    private String type;

    /**
     * Largura
     */
    private Integer Width;

    /**
     * Altura
     */
    private Integer Height;

    /**
     * Construtor da clase Key.
     * Herda da classe Action.
     * 
     * @param time - Tempo
     * @param cursor - Cursor
     * @param value - Valor
     * @param action - Ação
     * @param type - Tipo
     * @param Width - Largura
     * @param Height - Altura
     */
    public Key(Integer time, Integer cursor, String value, String action,String type, Integer Width, Integer Height) {
        super(time, cursor, value, action);
        this.type = type;
        this.Width = Width;
        this.Height = Height;
    }

    /**
     * Método get da variável Type
     * @return the type
     */
    public String getType() {
        return type;
    }

    /**
     * Método set da variável type
     * @param type the type to set
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Método get da variável Width
     * @return the Width
     */
    public Integer getWidth() {
        return Width;
    }

    /**
     * Método set da variável Width
     * @param Width the Width to set
     */
    public void setWidth(Integer Width) {
        this.Width = Width;
    }

    /**
     * Método get da variável Height
     * @return the Height
     */
    public Integer getHeight() {
        return Height;
    }

    /**
     * Método set da variável Height
     * @param Height the Height to set
     */
    public void setHeight(Integer Height) {
        this.Height = Height;
    }
    
    
}
