/**
 * LRSB - Linear Representation Spreedsheat Builder - Pauses Analysis of XML files generated by Translog II software. 
 * For Translog II details, see http://bridge.cbs.dk/platform/?q=Translog-II.
 * 
 * Developed with a grant from the Federal University of Uberlândia, Brazil (Project 2014PBG000883, Supervisor: 
 * Prof. Dr. Igor A. Lourenço da Silva)
 * 
 * Copyright (C) 2015 Gabriel Ed. da Silva
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General 
 * Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see
* http://www.gnu.org/licenses/.
 */

package com.lrsb.model;

/**
 * @author gabriel
 */
public class ConsolidatedDocument {
    
    /**
     * CSV Header
     */
    public static final String HEADER = createHeader();
    
    /**
     * Variables
     */

    private String subject;
    private Double totalDuration;
    private Double totalFixCountS;
    private Double totalFixDurS;
    private Double totalMeanFixS;
    private Double totalFixCountT;
    private Double totalFixDurT;
    private Double totalFixCountST;
    private Double totalFixDurST;
    private Double totalVisits;
    private Double totalIns;
    private Double totalDel;
    private Integer ptotalFixCountS;
    private Integer ptotalFixDurS;
    private Integer ptotalFixCountT;
    private Integer ptotalFixDurT;
    private Integer ptotalFixCountST;
    private Integer ptotalVisits;
    
    
    public ConsolidatedDocument(){
            totalDuration=0.0;
            totalFixCountS=0.0;
            totalFixDurS=0.0;
            totalMeanFixS=0.0;
            totalFixCountT=0.0;
            totalFixDurT=0.0;
            totalFixCountST=0.0;
            totalFixDurST=0.0;
            totalVisits=0.0;
            totalIns=0.0;
            totalDel=0.0;
            ptotalFixCountS=0;
            ptotalFixDurS=0;
            ptotalFixCountT=0;
            ptotalFixDurT=0;
            ptotalFixCountST=0;
            ptotalVisits=0;
    }
    
    /**
     * Inicialize a consolidated document
     * @param doc Documento to be consolidated
     */
    public void consolidatedDocumentInit(Document doc){        
        setSubject(doc.getSubject());   
    }
    
    /**
     * @return the subject
     */
    public String getSubject() {
        return subject;
    }

    /**
     * @param subject the subject to set
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * @return the totalDuration
     */
    public Double getTotalDuration() {
        return totalDuration;
    }

    /**
     * @param totalDuration the totalDuration to set
     */
    public void setTotalDuration(Double totalDuration) {
        this.totalDuration = totalDuration;
    }

    /**
     * @return the totalFixCountS
     */
    public Double getTotalFixCountS() {
        return totalFixCountS;
    }

    /**
     * @param totalFixCountS the totalFixCountS to set
     */
    public void setTotalFixCountS(Double totalFixCountS) {
        this.totalFixCountS = totalFixCountS;
    }

    /**
     * @return the totalFixDurS
     */
    public Double getTotalFixDurS() {
        return totalFixDurS;
    }

    /**
     * @param totalFixDurS the totalFixDurS to set
     */
    public void setTotalFixDurS(Double totalFixDurS) {
        this.totalFixDurS = totalFixDurS;
    }

    /**
     * @return the totalMeanFixS
     */
    public Double getTotalMeanFixS() {
        return totalMeanFixS;
    }

    /**
     * @param totalMeanFixS the totalMeanFixS to set
     */
    public void setTotalMeanFixS(Double totalMeanFixS) {
        this.totalMeanFixS = totalMeanFixS;
    }

    /**
     * @return the totalFixCountT
     */
    public Double getTotalFixCountT() {
        return totalFixCountT;
    }

    /**
     * @param totalFixCountT the totalFixCountT to set
     */
    public void setTotalFixCountT(Double totalFixCountT) {
        this.totalFixCountT = totalFixCountT;
    }

    /**
     * @return the totalFixDurT
     */
    public Double getTotalFixDurT() {
        return totalFixDurT;
    }

    /**
     * @param totalFixDurT the totalFixDurT to set
     */
    public void setTotalFixDurT(Double totalFixDurT) {
        this.totalFixDurT = totalFixDurT;
    }

    /**
     * @return the totalFixCountST
     */
    public Double getTotalFixCountST() {
        return totalFixCountST;
    }

    /**
     * @param totalFixCountST the totalFixCountST to set
     */
    public void setTotalFixCountST(Double totalFixCountST) {
        this.totalFixCountST = totalFixCountST;
    }

    /**
     * @return the totalFixDurST
     */
    public Double getTotalFixDurST() {
        return totalFixDurST;
    }

    /**
     * @param totalFixDurST the totalFixDurST to set
     */
    public void setTotalFixDurST(Double totalFixDurST) {
        this.totalFixDurST = totalFixDurST;
    }

    /**
     * @return the totalVisits
     */
    public Double getTotalVisits() {
        return totalVisits;
    }

    /**
     * @param totalVisits the totalVisits to set
     */
    public void setTotalVisits(Double totalVisits) {
        this.totalVisits = totalVisits;
    }

    /**
     * @return the totalIns
     */
    public Double getTotalIns() {
        return totalIns;
    }

    /**
     * @param totalIns the totalIns to set
     */
    public void setTotalIns(Double totalIns) {
        this.totalIns = totalIns;
    }

    /**
     * @return the totalDel
     */
    public Double getTotalDel() {
        return totalDel;
    }

    /**
     * @param totalDel the totalDel to set
     */
    public void setTotalDel(Double totalDel) {
        this.totalDel = totalDel;
    }

    /**
     * @return the ptotalFixCountS
     */
    public Integer getPtotalFixCountS() {
        return ptotalFixCountS;
    }

    /**
     * @param ptotalFixCountS the ptotalFixCountS to set
     */
    public void setPtotalFixCountS(Integer ptotalFixCountS) {
        this.ptotalFixCountS = ptotalFixCountS;
    }

    /**
     * @return the ptotalFixDurS
     */
    public Integer getPtotalFixDurS() {
        return ptotalFixDurS;
    }

    /**
     * @param ptotalFixDurS the ptotalFixDurS to set
     */
    public void setPtotalFixDurS(Integer ptotalFixDurS) {
        this.ptotalFixDurS = ptotalFixDurS;
    }

    /**
     * @return the ptotalFixCountT
     */
    public Integer getPtotalFixCountT() {
        return ptotalFixCountT;
    }

    /**
     * @param ptotalFixCountT the ptotalFixCountT to set
     */
    public void setPtotalFixCountT(Integer ptotalFixCountT) {
        this.ptotalFixCountT = ptotalFixCountT;
    }

    /**
     * @return the ptotalFixDurT
     */
    public Integer getPtotalFixDurT() {
        return ptotalFixDurT;
    }

    /**
     * @param ptotalFixDurT the ptotalFixDurT to set
     */
    public void setPtotalFixDurT(Integer ptotalFixDurT) {
        this.ptotalFixDurT = ptotalFixDurT;
    }

    /**
     * @return the ptotalFixCountST
     */
    public Integer getPtotalFixCountST() {
        return ptotalFixCountST;
    }

    /**
     * @param ptotalFixCountST the ptotalFixCountST to set
     */
    public void setPtotalFixCountST(Integer ptotalFixCountST) {
        this.ptotalFixCountST = ptotalFixCountST;
    }

    /**
     * @return the ptotalVisits
     */
    public Integer getPtotalVisits() {
        return ptotalVisits;
    }

    /**
     * @param ptotalVisits the ptotalVisits to set
     */
    public void setPtotalVisits(Integer ptotalVisits) {
        this.ptotalVisits = ptotalVisits;
    }
    
    public String toCSV(){
        String st;
                st = this.subject
                +","+this.getTotalDuration()
                +","+this.getTotalFixCountS()
                +","+this.getTotalFixDurS()
                +","+this.getTotalFixCountT()
                +","+this.getTotalFixDurT()
                +","+this.getTotalFixCountST()
                +","+this.getTotalFixDurST()
                +","+this.getTotalVisits()
                +","+this.getTotalIns()
                +","+this.getTotalDel()
                +","+this.getPtotalFixCountS()
                +","+this.getPtotalFixDurS()
                +","+this.getPtotalFixCountT()
                +","+this.getPtotalFixDurT()
                +","+this.getPtotalFixCountST()
                +","+this.getPtotalVisits()+"\n";
        System.out.println("st");
        return st;
    }

    private static String createHeader() {
        return  "sep=,\n"
            +"Subject"
            +",TotalDuration"
            +",TotalFixCountS"
            +",TotalFixDurS"
            +",TotalFixCountT"
            +",TotalFixDurT"
            +",TotalFixCountST"
            +",TotalFixDurS&T"
            +",TotalVisits"
            +",TotalIns"
            +",TotalDel" 
            +",PtotalFixCountS"
            +",PtotalFixDurS" 
            +",PtotalFixCountT"
            + ",PtotalFixDurT"
            +",PtotalFixCountST"
            +",PtotalVisits"
            +"\n";
    }
}
